### ISSUE TITLE
Build wheel fails for opencv-python-headless

### ISSUE THREAD

**Issue by yahyaakli** [opencv/opencv-python#651] opened 2022-04-06 17:30 UTC
I am using docker Alpine linux and I've been having issues with building wheel for opencv-python-headless. Everytime I run it I get this error:

```
**Traceback (most recent call last):
        File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-uka6wdi1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-uka6wdi1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir        
          self.run_setup()
        File "/tmp/pip-build-env-uka6wdi1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-uka6wdi1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 448, in <module>
          main()
        File "setup.py", line 210, in main
          skbuild.setup(
        File "/tmp/pip-build-env-uka6wdi1/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 676, in setup
          _classify_installed_files(
        File "setup.py", line 388, in _classify_installed_files_override
          return (cls.wraps._classify_installed_files)(
      TypeError: _classify_installed_files() got an unexpected keyword argument 'cmake_install_dir'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for opencv-python-headless**
```
(I am using alpine:3.14)

This seemed to me as a code issue.

Please, do you have any feedback on this issue?

Thank you.

**Comment by skvark** [comment] 2022-04-06 19:38
Duplicate of https://github.com/opencv/opencv-python/issues/648

**Comment by rooseveltrp** [comment] 2022-04-06 19:50
The PR mentioned `#648` does solve the issue. Here's my output:

```
$ git clone --recursive https://github.com/orbisvicis/opencv-python.git
$ cd opencv-python
$ git checkout 96cffde198e5bc3411a9577b97021ce59477f97a
$ pip wheel . --verbose
...
  adding 'opencv_python-4.5.5+96cffde.dist-info/top_level.txt'
  adding 'opencv_python-4.5.5+96cffde.dist-info/RECORD'
  removing _skbuild/linux-x86_64-3.6/setuptools/bdist.linux-x86_64/wheel
  Building wheel for opencv-python (pyproject.toml) ... done
  Created wheel for opencv-python: filename=opencv_python-4.5.5+96cffde-cp36-cp36m-linux_x86_64.whl size=28270789 sha256=11bfcaa97fd397dca117db96126b157e074f07f0ad8d1b6285faee4ef4be12c5
  Stored in directory: /root/.cache/pip/wheels/00/12/be/0f0afacf8c6e9a933c55fedf8e9168985722099e5a84c4ec10
Successfully built opencv-python
```

**Closed** 2022-04-08 05:13 UTC
Labels: duplicate
