### ISSUE TITLE
Failed to build wheel when installing with pip --no-binary. Got TypeError in setup.py

### ISSUE THREAD

**Issue by ThankPan** [opencv/opencv-python#649] opened 2022-04-06 15:17 UTC
### Actual behaviour

I'm trying to install with pip --no-binary following the instruction mentioned here https://stackoverflow.com/a/63839383/9982130 to solve another problem that I encountered. During the building wheel process, I got:
TypeError: _classify_installed_files() got an unexpected keyword argument 'cmake_install_dir'.

Traceback (most recent call last):
    File "/home/reinht/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/reinht/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/reinht/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-h4n0_raq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-h4n0_raq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-h4n0_raq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-h4n0_raq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 503, in <module>
      main()
    File "setup.py", line 240, in main
      skbuild.setup(
    File "/tmp/pip-build-env-h4n0_raq/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 676, in setup
      _classify_installed_files(
    File "setup.py", line 443, in _classify_installed_files_override
      return (cls.wraps._classify_installed_files)(

I could not understand what caused it.

### Steps to reproduce

- Ubuntu 20.04
- architecture: x86
- -python version: 3.9.7

**Comment by skvark** [comment] 2022-04-06 19:40
Duplicate of https://github.com/opencv/opencv-python/issues/648

**Comment by asmorkalov** [comment] 2022-04-07 05:10
https://github.com/opencv/opencv-python/pull/637

**Comment by asenyaev** [comment] 2022-04-07 10:27
https://github.com/opencv/opencv-python/pull/637 is merged into master, should fix this problem. Please, update your local opencv-python repository.

**Closed by asenyaev** 2022-04-07 10:27 UTC
Labels: duplicate
