### ISSUE TITLE
connectedComponentsWithStats produces a segfault in the latest release (4.5.5.62)

### ISSUE THREAD

**Issue by Dobiasd** [opencv/opencv-python#604] opened 2022-01-03 15:20 UTC
The following minimal example finishes with exit code 139 (interrupted by signal 11: SIGSEGV):

```python3
import cv2
import numpy as np

img = np.zeros((240, 320, 1), np.uint8)

cv2.connectedComponentsWithStats(img, connectivity=4)
cv2.connectedComponentsWithStats(img, connectivity=4)
```

With the previous release of `opencv-python` (`4.5.4.60`) this worked fine.

Here is a `Dockerfile` to reproduce the crash:

```Dockerfile
FROM python:3.9.9

RUN apt-get update && apt-get install -y \
  libglib2.0-0 \
  libgl1-mesa-glx \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

# With the old opencv-python==4.5.4.60 things are fine.
RUN pip install --no-cache-dir numpy==1.22.0 opencv-python==4.5.5.62

RUN echo "import cv2" > main.py
RUN echo "import numpy as np" >> main.py
RUN echo "img = np.zeros((240, 320, 1), np.uint8)" >> main.py
RUN echo "cv2.connectedComponentsWithStats(img, connectivity=4)" >> main.py
RUN echo "cv2.connectedComponentsWithStats(img, connectivity=4)" >> main.py

RUN python main.py
```

Result:

```
Segmentation fault (core dumped)
```

**Comment by Dobiasd** [comment] 2022-01-03 15:23
I don't know if relevant, but when installing `4.5.4.60`, `pip` prints:

```
Collecting opencv-python==4.5.4.60
  Downloading opencv_python-4.5.4.60-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.3 MB)
```

While when installing `4.5.5.62`, it prints:

```
Collecting opencv-python==4.5.5.62
  Downloading opencv_python-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.4 MB)
```

(`cp36-abi3` instead of `cp39-cp39`)

Maybe this is related to the problem?

**Comment by skvark** [comment] 2022-01-03 15:32
Duplicate of https://github.com/opencv/opencv-python/issues/602 and https://github.com/opencv/opencv/issues/21366.

Cannot be fixed here, the issue is in C++ code.

> (cp36-abi3 instead of cp39-cp39)

That is expected due to recent changes. See https://www.python.org/dev/peps/pep-0384/ for more info.

**Closed by skvark** 2022-01-03 15:32 UTC

**Comment by Dobiasd** [comment] 2022-01-03 15:37
Ah, ok, thanks. :+1:

**Comment by yanggyu17** [comment] 2022-03-11 00:11
it works 
opencv-python 4.5.4.60
thanks
