### ISSUE TITLE
Wheels not being used for 4.5.5.62 on M1

### ISSUE THREAD

**Issue by LKay** [opencv/opencv-python#620] opened 2022-02-04 15:20 UTC
### Expected behaviour

Pip downloads wheel and not try to rebuild everything or build is successful.

### Actual behaviour

Opencv is being rebuilt instead of using wheel and fails with error:
```
        Traceback (most recent call last):

        An error occurred while building with CMake.
          Command:
            cmake --build . --target install --config Release --
          Source directory:
            /private/var/folders/dp/wbrgl9_545bgfc6y8_sqj1dr0000gn/T/pip-req-build-up8nnspd
          Working directory:
            /private/var/folders/dp/wbrgl9_545bgfc6y8_sqj1dr0000gn/T/pip-req-build-up8nnspd/_skbuild/macosx-12.0-arm64-3.8/cmake-build
        Please see CMake's output for more information.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for opencv-python-headless
  Failed to build opencv-python-headless
  ERROR: Could not build wheels for opencv-python-headless, which is required to install pyproject.toml-based projects
```

### Steps to reproduce

- operating system
MacOS Monterey 12.1
- architecture (e.g. x86)
Apple M1 (arm64)
- opencv-python version
`opencv-python-headless@4.5.5.62`

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asenyaev** [comment] 2022-02-22 16:20
@LKay, could you give me your commands for a reproducing?

I tried just to do a force re-installation w/o cache and it was installed from PyPi, and wasn't built.

How I tried to reproduce:
```
python3.9 -m pip install --no-cache --force-reinstall opencv-python-headless==4.5.5.62

Collecting opencv-python-headless==4.5.5.62
  Downloading opencv_python_headless-4.5.5.62-cp37-abi3-macosx_11_0_arm64.whl (27.9 MB)
     |████████████████████████████████| 27.9 MB 12.0 MB/s            
Collecting numpy>=1.21.2
  Downloading numpy-1.22.2-cp39-cp39-macosx_11_0_arm64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 12.1 MB/s            
Installing collected packages: numpy, opencv-python-headless
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.1
    Uninstalling numpy-1.22.1:
      Successfully uninstalled numpy-1.22.1
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.5.5.62
    Uninstalling opencv-python-headless-4.5.5.62:
      Successfully uninstalled opencv-python-headless-4.5.5.62
Successfully installed numpy-1.22.2 opencv-python-headless-4.5.5.62
```

Also tried several python versions and the output was the same.

**Comment by asenyaev** [comment] 2022-03-02 10:13
Hi, @LKay!

I also tried to install a package on MacOS 12.X and there are no issues too.

How I tried to reproduce:

```
Collecting opencv-python-headless==4.5.5.62
  Downloading opencv_python_headless-4.5.5.62-cp37-abi3-macosx_11_0_arm64.whl (27.9 MB)
     |████████████████████████████████| 27.9 MB 5.3 MB/s
Collecting numpy>=1.14.5
  Downloading numpy-1.22.2-cp39-cp39-macosx_11_0_arm64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 5.8 MB/s
Installing collected packages: numpy, opencv-python-headless
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed numpy-1.22.2 opencv-python-headless-4.5.5.62
```

**Comment by asmorkalov** [comment] 2022-03-10 06:11
@LKay Do you have any updates?

**Comment by LKay** [comment] 2022-03-10 06:17
@asmorkalov Sorry, I missed previous notification. I have some workaround, so it works, but in general it's hit or miss. Sometimes it fetches it correctly and sometimes tries to rebuild the wheel. I use Poetry as python virtual environment tool, so if I create new, fresh environemnt for a project it sometimes tries to rebuild. 

As a workaround if this fails when I run `poetry update` or `poetry lock` I need to install the package manually inside the environment by running `poetry run pip install opencv-python-headless` and after the poetry commands pick it up. Not ideal, but at least it works that way.

**Comment by asmorkalov** [comment] 2022-03-10 09:07
I got the point. I close the issue for now. Please return back and reopen the issue in case if you find a way to reproduce the issue with pip. It looks like poetry tries to get some older version of OpenCV that is not present in pypi as binary for MacOS 12.

**Closed by asmorkalov** 2022-03-10 09:07 UTC
Labels: incomplete
